name: gh-pages

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/cache
            !~/cache/exclude
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      - name: npm install, build
        run: |
          npm i
          npm run build --if-present
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2.10.1
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_ACTIONS }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./dist
